// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdgNFtEDSg4P8q7gCFrCHGjGLewRbPoc',
    appId: '1:236067970113:web:79ddf4be42e7d2b1dc7ac0',
    messagingSenderId: '236067970113',
    projectId: 'todotask001-35f42',
    authDomain: 'todotask001-35f42.firebaseapp.com',
    storageBucket: 'todotask001-35f42.appspot.com',
    measurementId: 'G-192R7SFEZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8V66dZCpiOaJGaeokH2--LU3lGrs9OMw',
    appId: '1:236067970113:android:74f9d88bf44508fedc7ac0',
    messagingSenderId: '236067970113',
    projectId: 'todotask001-35f42',
    storageBucket: 'todotask001-35f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuYMA9lp1TxrWMnlARghgiJvKNSqtVUxg',
    appId: '1:236067970113:ios:5b8379f58c87ef99dc7ac0',
    messagingSenderId: '236067970113',
    projectId: 'todotask001-35f42',
    storageBucket: 'todotask001-35f42.appspot.com',
    iosBundleId: 'com.example.todotask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuYMA9lp1TxrWMnlARghgiJvKNSqtVUxg',
    appId: '1:236067970113:ios:5b8379f58c87ef99dc7ac0',
    messagingSenderId: '236067970113',
    projectId: 'todotask001-35f42',
    storageBucket: 'todotask001-35f42.appspot.com',
    iosBundleId: 'com.example.todotask1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAdgNFtEDSg4P8q7gCFrCHGjGLewRbPoc',
    appId: '1:236067970113:web:ab5754fd9d272117dc7ac0',
    messagingSenderId: '236067970113',
    projectId: 'todotask001-35f42',
    authDomain: 'todotask001-35f42.firebaseapp.com',
    storageBucket: 'todotask001-35f42.appspot.com',
    measurementId: 'G-B87N0C5ZHP',
  );
}
